// <auto-generated />
using System;
using Library.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.DAL.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Library.DAL.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 10, 14, 10, 52, 763, DateTimeKind.Local).AddTicks(3970),
                            Description = "Ipsam dolores ad possimus cumque autem adipisci quas.",
                            Name = "quia",
                            PageCount = 469,
                            UpdatedAt = new DateTime(2023, 3, 10, 14, 10, 52, 763, DateTimeKind.Local).AddTicks(3970)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 7, 13, 10, 12, 24, 339, DateTimeKind.Local).AddTicks(7047),
                            Description = "Dolor aliquid molestiae ipsam quasi aut.",
                            Name = "quod",
                            PageCount = 256,
                            UpdatedAt = new DateTime(2022, 7, 13, 10, 12, 24, 339, DateTimeKind.Local).AddTicks(7047)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 10, 20, 22, 49, 783, DateTimeKind.Local).AddTicks(8361),
                            Description = "Voluptas error qui aut sed quo.",
                            Name = "minus",
                            PageCount = 287,
                            UpdatedAt = new DateTime(2022, 6, 10, 20, 22, 49, 783, DateTimeKind.Local).AddTicks(8361)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 8, 3, 15, 9, 56, 632, DateTimeKind.Local).AddTicks(676),
                            Description = "Animi voluptate corrupti perspiciatis.",
                            Name = "doloribus",
                            PageCount = 500,
                            UpdatedAt = new DateTime(2022, 8, 3, 15, 9, 56, 632, DateTimeKind.Local).AddTicks(676)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 5, 5, 11, 15, 16, 294, DateTimeKind.Local).AddTicks(8391),
                            Description = "Nisi itaque et soluta qui illo quia.",
                            Name = "expedita",
                            PageCount = 121,
                            UpdatedAt = new DateTime(2022, 5, 5, 11, 15, 16, 294, DateTimeKind.Local).AddTicks(8391)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 10, 29, 10, 53, 9, 87, DateTimeKind.Local).AddTicks(2368),
                            Description = "Tempora eaque optio a et expedita impedit corporis est quo.",
                            Name = "illo",
                            PageCount = 266,
                            UpdatedAt = new DateTime(2021, 10, 29, 10, 53, 9, 87, DateTimeKind.Local).AddTicks(2368)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 10, 31, 15, 36, 36, 61, DateTimeKind.Local).AddTicks(2259),
                            Description = "Animi dolorem assumenda eos vel.",
                            Name = "quaerat",
                            PageCount = 192,
                            UpdatedAt = new DateTime(2022, 10, 31, 15, 36, 36, 61, DateTimeKind.Local).AddTicks(2259)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 4, 1, 20, 37, 41, 505, DateTimeKind.Local).AddTicks(345),
                            Description = "Minima quibusdam omnis neque aut in et autem asperiores rem.",
                            Name = "ipsam",
                            PageCount = 378,
                            UpdatedAt = new DateTime(2022, 4, 1, 20, 37, 41, 505, DateTimeKind.Local).AddTicks(345)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 27, 12, 55, 13, 194, DateTimeKind.Local).AddTicks(3807),
                            Description = "Ducimus qui necessitatibus nostrum exercitationem non cum et a consequatur.",
                            Name = "aspernatur",
                            PageCount = 219,
                            UpdatedAt = new DateTime(2022, 1, 27, 12, 55, 13, 194, DateTimeKind.Local).AddTicks(3807)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2023, 6, 15, 11, 45, 36, 696, DateTimeKind.Local).AddTicks(946),
                            Description = "Ullam laboriosam id totam voluptates aspernatur.",
                            Name = "tempora",
                            PageCount = 238,
                            UpdatedAt = new DateTime(2023, 6, 15, 11, 45, 36, 696, DateTimeKind.Local).AddTicks(946)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 9, 14, 8, 6, 15, 128, DateTimeKind.Local).AddTicks(2948),
                            Description = "Mollitia ut molestiae laudantium atque quas.",
                            Name = "consequuntur",
                            PageCount = 290,
                            UpdatedAt = new DateTime(2022, 9, 14, 8, 6, 15, 128, DateTimeKind.Local).AddTicks(2948)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2023, 4, 7, 3, 58, 54, 806, DateTimeKind.Local).AddTicks(2528),
                            Description = "Quia minima quos accusantium dolor eum ut esse quo velit.",
                            Name = "et",
                            PageCount = 404,
                            UpdatedAt = new DateTime(2023, 4, 7, 3, 58, 54, 806, DateTimeKind.Local).AddTicks(2528)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2023, 3, 18, 11, 13, 11, 168, DateTimeKind.Local).AddTicks(6592),
                            Description = "Beatae expedita minus quaerat vero alias.",
                            Name = "ipsum",
                            PageCount = 269,
                            UpdatedAt = new DateTime(2023, 3, 18, 11, 13, 11, 168, DateTimeKind.Local).AddTicks(6592)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 2, 8, 16, 19, 48, 22, DateTimeKind.Local).AddTicks(8591),
                            Description = "Eligendi reprehenderit consequatur numquam vel blanditiis.",
                            Name = "praesentium",
                            PageCount = 427,
                            UpdatedAt = new DateTime(2022, 2, 8, 16, 19, 48, 22, DateTimeKind.Local).AddTicks(8591)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 2, 12, 17, 16, 56, 61, DateTimeKind.Local).AddTicks(8845),
                            Description = "Dicta voluptatem pariatur quo quis.",
                            Name = "ex",
                            PageCount = 286,
                            UpdatedAt = new DateTime(2022, 2, 12, 17, 16, 56, 61, DateTimeKind.Local).AddTicks(8845)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 2, 14, 8, 19, 6, 452, DateTimeKind.Local).AddTicks(7971),
                            Description = "Porro nihil laboriosam minus provident.",
                            Name = "alias",
                            PageCount = 222,
                            UpdatedAt = new DateTime(2022, 2, 14, 8, 19, 6, 452, DateTimeKind.Local).AddTicks(7971)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2023, 2, 13, 0, 22, 16, 714, DateTimeKind.Local).AddTicks(6670),
                            Description = "Nobis dolores iusto eaque illum.",
                            Name = "assumenda",
                            PageCount = 92,
                            UpdatedAt = new DateTime(2023, 2, 13, 0, 22, 16, 714, DateTimeKind.Local).AddTicks(6670)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2023, 2, 28, 20, 33, 37, 672, DateTimeKind.Local).AddTicks(5215),
                            Description = "Ab eaque vel sunt hic et.",
                            Name = "temporibus",
                            PageCount = 440,
                            UpdatedAt = new DateTime(2023, 2, 28, 20, 33, 37, 672, DateTimeKind.Local).AddTicks(5215)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 11, 1, 13, 50, 58, 461, DateTimeKind.Local).AddTicks(4923),
                            Description = "Voluptatem aut sit ipsum atque a quod est ex.",
                            Name = "inventore",
                            PageCount = 347,
                            UpdatedAt = new DateTime(2022, 11, 1, 13, 50, 58, 461, DateTimeKind.Local).AddTicks(4923)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2023, 1, 5, 23, 50, 8, 296, DateTimeKind.Local).AddTicks(8956),
                            Description = "Nobis error sequi vero et quae sed.",
                            Name = "fugiat",
                            PageCount = 390,
                            UpdatedAt = new DateTime(2023, 1, 5, 23, 50, 8, 296, DateTimeKind.Local).AddTicks(8956)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 11, 29, 13, 4, 34, 967, DateTimeKind.Local).AddTicks(2018),
                            Description = "Dolor sapiente rerum qui.",
                            Name = "dolores",
                            PageCount = 391,
                            UpdatedAt = new DateTime(2022, 11, 29, 13, 4, 34, 967, DateTimeKind.Local).AddTicks(2018)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2023, 2, 16, 17, 13, 56, 722, DateTimeKind.Local).AddTicks(1883),
                            Description = "Quia voluptatem placeat ullam.",
                            Name = "et",
                            PageCount = 208,
                            UpdatedAt = new DateTime(2023, 2, 16, 17, 13, 56, 722, DateTimeKind.Local).AddTicks(1883)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2021, 12, 19, 3, 34, 27, 511, DateTimeKind.Local).AddTicks(131),
                            Description = "Beatae ea reiciendis.",
                            Name = "tenetur",
                            PageCount = 108,
                            UpdatedAt = new DateTime(2021, 12, 19, 3, 34, 27, 511, DateTimeKind.Local).AddTicks(131)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2023, 9, 3, 3, 52, 42, 666, DateTimeKind.Local).AddTicks(5738),
                            Description = "Optio aut quibusdam quae repellat voluptatem.",
                            Name = "eius",
                            PageCount = 436,
                            UpdatedAt = new DateTime(2023, 9, 3, 3, 52, 42, 666, DateTimeKind.Local).AddTicks(5738)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 3, 11, 13, 12, 59, 153, DateTimeKind.Local).AddTicks(6182),
                            Description = "Amet reprehenderit occaecati aut animi recusandae.",
                            Name = "quidem",
                            PageCount = 465,
                            UpdatedAt = new DateTime(2022, 3, 11, 13, 12, 59, 153, DateTimeKind.Local).AddTicks(6182)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2023, 1, 29, 5, 17, 47, 653, DateTimeKind.Local).AddTicks(5395),
                            Description = "Non recusandae ut aut provident repudiandae ut.",
                            Name = "magnam",
                            PageCount = 106,
                            UpdatedAt = new DateTime(2023, 1, 29, 5, 17, 47, 653, DateTimeKind.Local).AddTicks(5395)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2023, 1, 3, 14, 20, 39, 190, DateTimeKind.Local).AddTicks(9098),
                            Description = "Ut natus voluptatum magnam dolores.",
                            Name = "voluptate",
                            PageCount = 483,
                            UpdatedAt = new DateTime(2023, 1, 3, 14, 20, 39, 190, DateTimeKind.Local).AddTicks(9098)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2023, 2, 9, 4, 22, 9, 536, DateTimeKind.Local).AddTicks(9922),
                            Description = "Totam delectus fugit qui neque recusandae et et voluptatum rem.",
                            Name = "et",
                            PageCount = 74,
                            UpdatedAt = new DateTime(2023, 2, 9, 4, 22, 9, 536, DateTimeKind.Local).AddTicks(9922)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2023, 4, 27, 17, 54, 20, 454, DateTimeKind.Local).AddTicks(7962),
                            Description = "A omnis quod doloribus sint dicta nostrum minus.",
                            Name = "expedita",
                            PageCount = 366,
                            UpdatedAt = new DateTime(2023, 4, 27, 17, 54, 20, 454, DateTimeKind.Local).AddTicks(7962)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 11, 22, 16, 5, 21, 435, DateTimeKind.Local).AddTicks(256),
                            Description = "Fugiat quae possimus totam ut sed non quis ipsa natus.",
                            Name = "aut",
                            PageCount = 421,
                            UpdatedAt = new DateTime(2022, 11, 22, 16, 5, 21, 435, DateTimeKind.Local).AddTicks(256)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 10, 1, 12, 9, 49, 348, DateTimeKind.Local).AddTicks(876),
                            Description = "Atque ut est aut aliquid doloremque in.",
                            Name = "rerum",
                            PageCount = 431,
                            UpdatedAt = new DateTime(2022, 10, 1, 12, 9, 49, 348, DateTimeKind.Local).AddTicks(876)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 5, 10, 8, 10, 16, 152, DateTimeKind.Local).AddTicks(1771),
                            Description = "Ut accusamus dolor libero minus voluptatem.",
                            Name = "quos",
                            PageCount = 448,
                            UpdatedAt = new DateTime(2022, 5, 10, 8, 10, 16, 152, DateTimeKind.Local).AddTicks(1771)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 9, 27, 8, 35, 0, 583, DateTimeKind.Local).AddTicks(8797),
                            Description = "Eum enim aut.",
                            Name = "non",
                            PageCount = 274,
                            UpdatedAt = new DateTime(2022, 9, 27, 8, 35, 0, 583, DateTimeKind.Local).AddTicks(8797)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2022, 7, 29, 18, 19, 55, 381, DateTimeKind.Local).AddTicks(6746),
                            Description = "Tempore in itaque ullam aliquid.",
                            Name = "voluptate",
                            PageCount = 465,
                            UpdatedAt = new DateTime(2022, 7, 29, 18, 19, 55, 381, DateTimeKind.Local).AddTicks(6746)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2021, 10, 21, 21, 52, 13, 443, DateTimeKind.Local).AddTicks(2292),
                            Description = "Qui debitis beatae.",
                            Name = "reprehenderit",
                            PageCount = 218,
                            UpdatedAt = new DateTime(2021, 10, 21, 21, 52, 13, 443, DateTimeKind.Local).AddTicks(2292)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2023, 3, 8, 23, 44, 38, 261, DateTimeKind.Local).AddTicks(9733),
                            Description = "Architecto alias nam voluptatem et.",
                            Name = "provident",
                            PageCount = 188,
                            UpdatedAt = new DateTime(2023, 3, 8, 23, 44, 38, 261, DateTimeKind.Local).AddTicks(9733)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2023, 6, 7, 4, 30, 10, 543, DateTimeKind.Local).AddTicks(6317),
                            Description = "Molestiae dolores aspernatur deserunt quidem eum eum fuga.",
                            Name = "earum",
                            PageCount = 143,
                            UpdatedAt = new DateTime(2023, 6, 7, 4, 30, 10, 543, DateTimeKind.Local).AddTicks(6317)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2022, 7, 7, 10, 34, 0, 256, DateTimeKind.Local).AddTicks(595),
                            Description = "Explicabo dolorum hic quia minima est dignissimos.",
                            Name = "sed",
                            PageCount = 52,
                            UpdatedAt = new DateTime(2022, 7, 7, 10, 34, 0, 256, DateTimeKind.Local).AddTicks(595)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2022, 1, 26, 3, 33, 38, 727, DateTimeKind.Local).AddTicks(7560),
                            Description = "At quae itaque.",
                            Name = "quo",
                            PageCount = 274,
                            UpdatedAt = new DateTime(2022, 1, 26, 3, 33, 38, 727, DateTimeKind.Local).AddTicks(7560)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2023, 9, 8, 4, 37, 37, 584, DateTimeKind.Local).AddTicks(272),
                            Description = "Commodi aspernatur asperiores similique et nihil quas et ducimus.",
                            Name = "aliquam",
                            PageCount = 247,
                            UpdatedAt = new DateTime(2023, 9, 8, 4, 37, 37, 584, DateTimeKind.Local).AddTicks(272)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
